//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SharpReport.Designer {
	using System;
	using System.Drawing;
	
	
	/// <summary>
	/// This Class handles manipulation of reportitems, called from DragDrop or from Commands
	/// </summary>
	/// <remarks>
	/// 	created by - Forstmeier Peter
	/// 	created on - 20.01.2005 16:41:53
	/// </remarks>
	
	public delegate void ItemDragDropEventHandler (object sender, ItemDragDropEventArgs e);
	
	public class ItemDragDropEventArgs : System.EventArgs {
		
		public enum enmAction {
			Add,
			Remove
		}
		
		string itemName;
		enmAction action;
		Point itemAtPoint;

		public ItemDragDropEventArgs(enmAction action, Point itemAtPoint, string itemName){
			this.action = action;
			this.itemAtPoint = itemAtPoint;
			this.itemName = itemName;
		}
		
		public enmAction Action {
			get {
				return action;
			}
		}
		public Point ItemAtPoint {
			get {
				return itemAtPoint;
			}
		}
		public string ItemName {
			get {
				return itemName;
			}
		}
	}
}
