//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SharpReportCore {
	using System;
	using SharpReportCore;
	using System.Collections;
	
	/// <summary>
	/// 
	/// </summary>
	/// <remarks>
	/// 	created by - Forstmeier peter
	/// 	created on - 02.12.2005 13:42:08
	/// </remarks>
	public class IHierarchicalArray : ArrayList,IHierarchicalEnumerable {
		
		/// <summary>
		/// Default constructor - initializes all fields to default values
		/// </summary>
		public IHierarchicalArray(){
		}
		
		
		#region SharpReportCore.IHierarchicalEnumerable interface implementation
		public IHierarchyData GetHierarchyData(Object enumeratedItem) {
			return enumeratedItem as IHierarchyData;

		}
		#endregion
		
		
	}
}
