//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------


using System;
using System.Windows.Forms;
using System.Drawing;
using System.Drawing.Drawing2D;

using SharpReportCore;

/// <summary>
/// UserCOntrol for rectangle in the Designer
/// </summary>
/// <remarks>
/// 	created by - Forstmeier Peter
/// 	created on - 07.01.2005 15:50:40
/// </remarks>
namespace SharpReport.Designer {	
	internal class ReportRectangleControl : AbstractGraphicControl {
		
		RectangleShape shape = new RectangleShape();
		
		public ReportRectangleControl() {
			InitializeComponent();
			this.SetStyle(ControlStyles.DoubleBuffer |
			              ControlStyles.UserPaint |
			              ControlStyles.AllPaintingInWmPaint |
			              ControlStyles.ResizeRedraw,
			              true);
			this.UpdateStyles();
		}
		#region overrides
		
		protected override void OnPaint(System.Windows.Forms.PaintEventArgs pea) {
			base.OnPaint(pea);
			base.DrawDecorations(pea);

			shape.FillShape(pea.Graphics,
			                new SolidFillPattern(this.BackColor),
			                (RectangleF)base.FocusRectangle);
			
			shape.DrawShape (pea.Graphics,
			                 new BaseLine (this.ForeColor,base.DashStyle,base.Thickness),
			                 (RectangleF)base.FocusRectangle);
		}
		
		
		public override string ToString() {
			return this.Name;
		}
		#endregion
		
		
		#region Windows Forms Designer generated code
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent() {
			// 
			// ReportRectangleControl
			// 
			this.BackColor = System.Drawing.Color.White;
			this.Name = "ReportRectangleControl";
			this.Size = new System.Drawing.Size(72, 40);
		}
		#endregion
	}
}
