//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SharpReport {
	using System;
	
	using SharpReportCore;
	using SharpReport.Designer;
	/// <summary>
	/// Helper Class for Report Items
	/// </summary>
	/// <remarks>
	/// 	created by - Forstmeier Peter
	/// 	created on - 31.08.2005 13:49:47
	/// </remarks>
	public class ItemsHelper : object {
		
		
		public static void UpdateTextControl (ReportObjectControlBase control,
		                                      BaseReportItem item) {
			
			item.SuspendLayout();
			item.Size = control.Size;
			item.Location = control.Location;
			item.Name = control.Name;
			item.BackColor = control.BackColor;
			item.ForeColor = control.ForeColor;
			item.Font = control.Font;
			item.ResumeLayout();
		}
		
		public static void UpdateGraphicControl (AbstractGraphicControl control,
		                                  			BaseGraphicItem item) {
			
			ItemsHelper.UpdateTextControl (control,item);
			item.SuspendLayout();
			item.Thickness = control.Thickness;
			item.DashStyle = control.DashStyle;
			item.ResumeLayout();
		}
		
		
		public static void UpdateTextBase (ReportObjectControlBase control,
		                                   BaseReportItem item) {
			
//			control.SuspendLayout();
//			item.SuspendLayout();
			control.BackColor = item.BackColor;
			control.ForeColor = item.ForeColor;
			control.Location = item.Location;
			control.Size = item.Size;
			control.Font = item.Font; 
			BaseTextItem b = item as BaseTextItem;
			if (b != null) {
				control.StringAlignment = b.StringAlignment;
			}

//			item.ResumeLayout();
//			control.ResumeLayout();
		}
		
		
		public static void UpdateGraphicBase (AbstractGraphicControl control,
		                                   BaseGraphicItem item) {
			ItemsHelper.UpdateTextBase(control,item);
//			control.SuspendLayout();
//			item.SuspendLayout();
			control.Location = item.Location;
			control.DashStyle = item.DashStyle;
			control.Thickness = item.Thickness;
//			item.ResumeLayout();
//			control.ResumeLayout();
		}
	}
}
