//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SharpReportCore {
	using System;
	using System.Drawing;
	
	/// <summary>
	/// Section Interface 
	/// </summary>
	public interface IItemRenderer :IBaseRenderer  {

		string Name{
			get;
			set;
		}
		
		Size Size {
			get;set;
		}
		
		Point Location {
			get;set;
		}
		
		Font Font {
			get;set;
		}
	}
}
