//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SharpReportCore {
	using System;
	using System.ComponentModel;
	
	/// <summary>
	/// This Class represents a Column to sort
	/// </summary>
	/// <remarks>
	/// 	created by - Forstmeier Peter
	/// 	created on - 18.05.2005 11:34:45
	/// </remarks>
	public class SortColumn : AbstractColumn {
		ListSortDirection sortDirection = ListSortDirection.Ascending;
		bool caseSensitive;
		
		
		public SortColumn() {
		}
		
		public SortColumn(string columnName,Type type ):this(columnName,ListSortDirection.Ascending,type,false){
		}
		

		
		public SortColumn(string columnName,ListSortDirection sortDirection)
			:this(columnName,sortDirection,null,false){
		}
		
		public SortColumn(string columnName,ListSortDirection sortDirection,Type type)
			:this(columnName,sortDirection,type,false){
		}
		
		public SortColumn(string columnName, ListSortDirection sortDirection, Type type,bool caseSensitive ):base (columnName,type)
		{
			this.caseSensitive = caseSensitive;
			this.sortDirection = sortDirection;
		}
		
		#region propertie's

		
		public ListSortDirection SortDirection {
			get {
				return sortDirection;
			}
			set {
				sortDirection = value;
			}
		}
		public bool CaseSensitive {
			get {
				return caseSensitive;
			}
			set {
				caseSensitive = value;
			}
		}
		
		#endregion
	}
}
