// Copyright (c) 2014 AlphaSierraPapa for the SharpDevelop Team
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this
// software and associated documentation files (the "Software"), to deal in the Software
// without restriction, including without limitation the rights to use, copy, modify, merge,
// publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
// to whom the Software is furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
// FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

using System;
using System.IO;
using System.Xml;

namespace ICSharpCode.WixBinding
{
	public class WixBinaryElement : WixElementBase
	{
		public const string BinaryElementName = "Binary";
		
		public WixBinaryElement(WixDocument document) 
			: base(BinaryElementName, document)
		{
		}
		
		public string Source {
			get {
				if (HasAttribute("SourceFile")) {
					return GetAttribute("SourceFile");
				} 
				return GetAttribute("src");
			}
		}
		
		/// <summary>
		/// Gets the full filename including the root directory path to this binary.
		/// </summary>
		/// <remarks>
		/// The full path is generated by using the WixDocument's filename.
		/// </remarks>
		public string GetFileName()
		{
			string relativeFileName = WixPropertyParser.Parse(Source, OwnerWixDocument);
			return GetFullPath(relativeFileName);
		}
			
		string GetFullPath(string relativeFileName)
		{
			string documentFileName = OwnerWixDocument.FileName;
			if (!String.IsNullOrEmpty(documentFileName)) {
				return Path.Combine(Path.GetDirectoryName(documentFileName), relativeFileName);
			}
			return relativeFileName;
		}
	}
}
