//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------


using System;
using System.Drawing;
using System.Windows.Forms;

/// <summary>
/// This node act's as an Abstract Class for all Nodes used in the FieldsExplorer
/// 
/// Partially copied from ProjectBrowser/AbstractBrowserNode</summary>
/// <remarks>
/// 	created by - Forstmeier Peter
/// 	created on - 05.06.2005 18:30:32
/// </remarks>
namespace SharpReportAddin {
	
	public class AbstractFieldsNode : TreeNode {
		
		private string contextmenuAddinTreePath = String.Empty;
		
		protected AbstractFieldsNode() {
		}
		
		
		
		/// <summary>
		/// Generates a Drag & Drop data object. If this property returns null
		/// the node indicates that it can't be dragged.
		/// </summary>
		public virtual DataObject DragDropDataObject {
			get {
				return null;
			}
		}
		
		
		/// <summary>
		/// Gets the add-in tree path for the context menu. 
		/// </summary>
		/// <remarks>
		/// I choosed to give back the add-in tree path instead of a popup menu 
		/// or a menuitem collection, because I don't want to add a magic library 
		/// or Windows.Forms dependency.
		/// </remarks>
		
		public virtual string ContextmenuAddinTreePath {
			get {
				return contextmenuAddinTreePath;
			}
			set {
				contextmenuAddinTreePath = value;
			}
		}
//		public Image a_IconImage {
//			get {
//				return iconImage;
//			}
//			set {
//				iconImage = value;
//			}
//		}
		
	}
}
