//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace SharpReportCore {
	using System;
	
	
	/// <summary>
	/// 
	/// </summary>
	/// <remarks>
	/// 	created by - Forstmeier Peter
	/// 	created on - 21.06.2005 23:10:57
	/// </remarks>
	
	
	public class SharpReportEventArgs : System.EventArgs {
		
		/// <summary>
		/// Default constructor - initializes all fields to default values
		/// </summary>
		
		bool cancel = false;
		int pageNumber ;
		
		
		public SharpReportEventArgs():this(0){
		}
		
		public SharpReportEventArgs(int pageNumber) {
			this.pageNumber = pageNumber;
		}
		
		/// <summary>
		/// PageNr on witch this event occurres
		/// </summary>
		public int PageNumber {
			get {
				return pageNumber;
			}
			set {
				pageNumber = value;
			}
		}
		
		/// <summary>
		/// Cancel the Job
		/// </summary>
		public bool Cancel {
			get {
				return cancel;
			}
			set {
				cancel = value;
			}
		}
		
	}
}
