// <file>
//     <copyright see="prj:///doc/copyright.txt"/>
//     <license see="prj:///doc/license.txt"/>
//     <owner name="David Srbecký" email="dsrbecky@gmail.com"/>
//     <version>$Revision$</version>
// </file>

// This file is automatically generated - any changes will be lost

#pragma warning disable 1591

namespace Debugger.Wrappers.CorSym
{
	using System;
	
	
	public enum CorSymSearchPolicyAttributes : int
	{
		
		AllowRegistryAccess = 1,
		
		AllowSymbolServerAccess = 2,
		
		AllowOriginalPathAccess = 4,
		
		AllowReferencePathAccess = 8,
	}
}

#pragma warning restore 1591
