// <file>
//     <copyright see="prj:///doc/copyright.txt"/>
//     <license see="prj:///doc/license.txt"/>
//     <owner name="David Srbecký" email="dsrbecky@gmail.com"/>
//     <version>$Revision$</version>
// </file>

// This file is automatically generated - any changes will be lost

#pragma warning disable 1591

namespace Debugger.Wrappers.CorDebug
{
	using System;
	
	
	public enum CorDebugUnmappedStop : int
	{
		
		STOP_NONE = 0,
		
		STOP_PROLOG = 1,
		
		STOP_EPILOG = 2,
		
		STOP_NO_MAPPING_INFO = 4,
		
		STOP_OTHER_UNMAPPED = 8,
		
		STOP_UNMANAGED = 16,
		
		STOP_ALL = 65535,
	}
}

#pragma warning restore 1591
