// <file>
//     <copyright see="prj:///doc/copyright.txt"/>
//     <license see="prj:///doc/license.txt"/>
//     <owner name="David Srbecký" email="dsrbecky@gmail.com"/>
//     <version>$Revision$</version>
// </file>

// This file is automatically generated - any changes will be lost

#pragma warning disable 1591

namespace Debugger.Wrappers.CorDebug
{
	using System;
	
	
	public partial class ICorDebugTypeEnum
	{
		
		private Debugger.Interop.CorDebug.ICorDebugTypeEnum wrappedObject;
		
		internal Debugger.Interop.CorDebug.ICorDebugTypeEnum WrappedObject
		{
			get
			{
				return this.wrappedObject;
			}
		}
		
		public ICorDebugTypeEnum(Debugger.Interop.CorDebug.ICorDebugTypeEnum wrappedObject)
		{
			this.wrappedObject = wrappedObject;
			ResourceManager.TrackCOMObject(wrappedObject, typeof(ICorDebugTypeEnum));
		}
		
		public static ICorDebugTypeEnum Wrap(Debugger.Interop.CorDebug.ICorDebugTypeEnum objectToWrap)
		{
			if ((objectToWrap != null))
			{
				return new ICorDebugTypeEnum(objectToWrap);
			} else
			{
				return null;
			}
		}
		
		~ICorDebugTypeEnum()
		{
			object o = wrappedObject;
			wrappedObject = null;
			ResourceManager.ReleaseCOMObject(o, typeof(ICorDebugTypeEnum));
		}
		
		public bool Is<T>() where T: class
		{
			System.Reflection.ConstructorInfo ctor = typeof(T).GetConstructors()[0];
			System.Type paramType = ctor.GetParameters()[0].ParameterType;
			return paramType.IsInstanceOfType(this.WrappedObject);
		}
		
		public T As<T>() where T: class
		{
			try {
				return CastTo<T>();
			} catch {
				return null;
			}
		}
		
		public T CastTo<T>() where T: class
		{
			return (T)Activator.CreateInstance(typeof(T), this.WrappedObject);
		}
		
		public static bool operator ==(ICorDebugTypeEnum o1, ICorDebugTypeEnum o2)
		{
			return ((object)o1 == null && (object)o2 == null) ||
			       ((object)o1 != null && (object)o2 != null && o1.WrappedObject == o2.WrappedObject);
		}
		
		public static bool operator !=(ICorDebugTypeEnum o1, ICorDebugTypeEnum o2)
		{
			return !(o1 == o2);
		}
		
		public override int GetHashCode()
		{
			return base.GetHashCode();
		}
		
		public override bool Equals(object o)
		{
			ICorDebugTypeEnum casted = o as ICorDebugTypeEnum;
			return (casted != null) && (casted.WrappedObject == wrappedObject);
		}
		
		
		public void Skip(uint celt)
		{
			this.WrappedObject.Skip(celt);
		}
		
		public void Reset()
		{
			this.WrappedObject.Reset();
		}
		
		public ICorDebugEnum Clone()
		{
			ICorDebugEnum ppEnum;
			Debugger.Interop.CorDebug.ICorDebugEnum out_ppEnum;
			this.WrappedObject.Clone(out out_ppEnum);
			ppEnum = ICorDebugEnum.Wrap(out_ppEnum);
			return ppEnum;
		}
		
		public uint Count
		{
			get
			{
				uint pcelt;
				this.WrappedObject.GetCount(out pcelt);
				return pcelt;
			}
		}
		
		public uint Next(uint celt, ICorDebugType[] values)
		{
			uint pceltFetched;
			Debugger.Interop.CorDebug.ICorDebugType[] array_values = new Debugger.Interop.CorDebug.ICorDebugType[values.Length];
			for (int i = 0; (i < values.Length); i = (i + 1))
			{
				if ((values[i] != null))
				{
					array_values[i] = values[i].WrappedObject;
				}
			}
			this.WrappedObject.Next(celt, array_values, out pceltFetched);
			for (int i = 0; (i < values.Length); i = (i + 1))
			{
				if ((array_values[i] != null))
				{
					values[i] = ICorDebugType.Wrap(array_values[i]);
				} else
				{
					values[i] = null;
				}
			}
			return pceltFetched;
		}
	}
}

#pragma warning restore 1591
