using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Media;
using System.Windows;
using System.Windows.Input;
using System.Windows.Documents;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Shapes;
using System.Windows.Media.Animation;
using System.Windows.Data;

namespace ICSharpCode.WpfDesign.Designer.PropertyGrid
{
	public class BasicMetadata
	{
		public const string Category_Brushes = "Brushes";
		public const string Category_Text = "Text";
		public const string Category_Appearance = "Appearance";
		public const string Category_Layout = "Layout";
		public const string Category_Common_Properties = "Common Properties";
		public const string Category_Misc = "Misc";
		public const string Category_Transform = "Transform";
		public const string Category_Media = "Media";
		public const string Category_Light = "Light";
		public const string Category_Camera = "Camera";
		public const string Category_Materials = "Materials";

		public BasicMetadata()
		{
			Metadata.AddStandardValues(typeof(Brush), typeof(Brushes));
			Metadata.AddStandardValues(typeof(Color), typeof(Colors));
			Metadata.AddStandardValues(typeof(FontStretch), typeof(FontStretches));
			Metadata.AddStandardValues(typeof(FontWeight), typeof(FontWeights));
			Metadata.AddStandardValues(typeof(FontStyle), typeof(FontStyles));
			Metadata.AddStandardValues(typeof(Cursor), typeof(Cursors));
			Metadata.AddStandardValues(typeof(PixelFormat), typeof(PixelFormats));
			Metadata.AddStandardValues(typeof(TextDecorationCollection), typeof(TextDecorations));
			Metadata.AddStandardValues(typeof(FontFamily), Fonts.SystemFontFamilies);

			//Metadata.AddStandardValues(typeof(ICommand), typeof(ApplicationCommands));
			//Metadata.AddStandardValues(typeof(ICommand), typeof(EditingCommands));
			//Metadata.AddStandardValues(typeof(ICommand), typeof(NavigationCommands));
			//Metadata.AddStandardValues(typeof(ICommand), typeof(ComponentCommands));
			//Metadata.AddStandardValues(typeof(ICommand), typeof(MediaCommands));

			Metadata.CategoryOrder = new[]  {
				Category_Brushes,
				Category_Appearance,
				Category_Layout,
				Category_Common_Properties,
				Category_Text,
				Category_Transform,
				Category_Media,
				Category_Light,
				Category_Camera,
				Category_Brushes,
				Category_Materials,
				Category_Misc
			};

			Metadata.AddCategory(AccessText.TextProperty, Category_Text);
			Metadata.AddCategory(Block.BorderBrushProperty, Category_Appearance);
			Metadata.AddCategory(Block.BorderThicknessProperty, Category_Appearance);
			Metadata.AddCategory(Block.BreakColumnBeforeProperty, Category_Text);
			Metadata.AddCategory(Block.BreakPageBeforeProperty, Category_Text);
			Metadata.AddCategory(Block.LineHeightProperty, Category_Layout);
			Metadata.AddCategory(Block.MarginProperty, Category_Layout);
			Metadata.AddCategory(Block.PaddingProperty, Category_Layout);
			Metadata.AddCategory(Block.TextAlignmentProperty, Category_Text);
			Metadata.AddCategory(Border.BorderBrushProperty, Category_Brushes);
			Metadata.AddCategory(Border.BorderThicknessProperty, Category_Appearance);
			Metadata.AddCategory(Border.CornerRadiusProperty, Category_Appearance);
			Metadata.AddCategory(Border.PaddingProperty, Category_Layout);
			Metadata.AddCategory(Button.IsCancelProperty, Category_Common_Properties);
			Metadata.AddCategory(Button.IsDefaultProperty, Category_Common_Properties);
			Metadata.AddCategory(ButtonBase.ClickModeProperty, Category_Misc);
			Metadata.AddCategory(ButtonBase.CommandParameterProperty, Category_Misc);
			Metadata.AddCategory(ButtonBase.CommandProperty, Category_Misc);
			Metadata.AddCategory(ButtonBase.CommandTargetProperty, Category_Misc);
			Metadata.AddCategory(ButtonBase.IsPressedProperty, Category_Common_Properties);
			Metadata.AddCategory(Camera.TransformProperty, Category_Transform);
			Metadata.AddCategory(Canvas.BottomProperty, Category_Layout);
			Metadata.AddCategory(Canvas.LeftProperty, Category_Layout);
			Metadata.AddCategory(Canvas.RightProperty, Category_Layout);
			Metadata.AddCategory(Canvas.TopProperty, Category_Layout);
			Metadata.AddCategory(ColumnDefinition.MaxWidthProperty, Category_Layout);
			Metadata.AddCategory(ColumnDefinition.MinWidthProperty, Category_Layout);
			Metadata.AddCategory(ColumnDefinition.WidthProperty, Category_Layout);
			Metadata.AddCategory(ComboBox.IsDropDownOpenProperty, Category_Common_Properties);
			Metadata.AddCategory(ComboBox.IsEditableProperty, Category_Common_Properties);
			Metadata.AddCategory(ComboBox.StaysOpenOnEditProperty, Category_Common_Properties);
			Metadata.AddCategory(ComboBox.TextProperty, Category_Common_Properties);
			Metadata.AddCategory(ContentControl.ContentProperty, Category_Common_Properties);
			Metadata.AddCategory(ContentControl.ContentTemplateProperty, Category_Misc);
			Metadata.AddCategory(ContentControl.ContentTemplateSelectorProperty, Category_Misc);
			Metadata.AddCategory(Control.HorizontalContentAlignmentProperty, Category_Layout);
			Metadata.AddCategory(Control.PaddingProperty, Category_Layout);
			Metadata.AddCategory(Control.VerticalContentAlignmentProperty, Category_Layout);
			Metadata.AddCategory(DashStyle.DashesProperty, Category_Appearance);
			Metadata.AddCategory(DiffuseMaterial.BrushProperty, Category_Appearance);
			Metadata.AddCategory(DirectionalLight.DirectionProperty, Category_Light);
			Metadata.AddCategory(DockPanel.DockProperty, Category_Layout);
			Metadata.AddCategory(DockPanel.LastChildFillProperty, Category_Layout);
			Metadata.AddCategory(DocumentViewer.ExtentHeightProperty, Category_Layout);
			Metadata.AddCategory(DocumentViewer.ExtentWidthProperty, Category_Layout);
			Metadata.AddCategory(DocumentViewer.HorizontalOffsetProperty, Category_Layout);
			Metadata.AddCategory(DocumentViewer.HorizontalPageSpacingProperty, Category_Layout);
			Metadata.AddCategory(DocumentViewer.ViewportHeightProperty, Category_Layout);
			Metadata.AddCategory(DocumentViewer.ViewportWidthProperty, Category_Layout);
			Metadata.AddCategory(DrawingGroup.ClipGeometryProperty, Category_Appearance);
			Metadata.AddCategory(DrawingGroup.OpacityProperty, Category_Appearance);
			Metadata.AddCategory(EllipseGeometry.CenterProperty, Category_Layout);
			Metadata.AddCategory(EmissiveMaterial.BrushProperty, Category_Appearance);
			Metadata.AddCategory(Expander.ExpandDirectionProperty, Category_Common_Properties);
			Metadata.AddCategory(Expander.IsExpandedProperty, Category_Common_Properties);
			Metadata.AddCategory(Figure.HeightProperty, Category_Layout);
			Metadata.AddCategory(Figure.HorizontalAnchorProperty, Category_Layout);
			Metadata.AddCategory(Figure.HorizontalOffsetProperty, Category_Layout);
			Metadata.AddCategory(Figure.VerticalAnchorProperty, Category_Layout);
			Metadata.AddCategory(Figure.VerticalOffsetProperty, Category_Layout);
			Metadata.AddCategory(Figure.WidthProperty, Category_Layout);
			Metadata.AddCategory(FixedPage.ContentBoxProperty, Category_Layout);
			Metadata.AddCategory(Floater.WidthProperty, Category_Layout);
			Metadata.AddCategory(FlowDocument.ColumnGapProperty, Category_Layout);
			Metadata.AddCategory(FlowDocument.ColumnRuleBrushProperty, Category_Layout);
			Metadata.AddCategory(FlowDocument.ColumnRuleWidthProperty, Category_Layout);
			Metadata.AddCategory(FlowDocument.ColumnWidthProperty, Category_Layout);
			Metadata.AddCategory(FlowDocument.IsColumnWidthFlexibleProperty, Category_Layout);
			Metadata.AddCategory(FormatConvertedBitmap.AlphaThresholdProperty, Category_Appearance);
			Metadata.AddCategory(Frame.NavigationUIVisibilityProperty, Category_Common_Properties);
			Metadata.AddCategory(Frame.SourceProperty, Category_Common_Properties);
			Metadata.AddCategory(FrameworkElement.ActualHeightProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.ActualWidthProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.CursorProperty, Category_Common_Properties);
			Metadata.AddCategory(FrameworkElement.DataContextProperty, Category_Common_Properties);
			Metadata.AddCategory(FrameworkElement.HeightProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.HorizontalAlignmentProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.LayoutTransformProperty, Category_Transform);
			Metadata.AddCategory(FrameworkElement.MarginProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.MaxHeightProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.MaxWidthProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.MinHeightProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.MinWidthProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.TagProperty, Category_Common_Properties);
			Metadata.AddCategory(FrameworkElement.VerticalAlignmentProperty, Category_Layout);
			Metadata.AddCategory(FrameworkElement.WidthProperty, Category_Layout);
			Metadata.AddCategory(Geometry.TransformProperty, Category_Transform);
			Metadata.AddCategory(GeometryDrawing.BrushProperty, Category_Appearance);
			Metadata.AddCategory(GeometryGroup.FillRuleProperty, Category_Appearance);
			Metadata.AddCategory(GeometryModel3D.BackMaterialProperty, Category_Materials);
			Metadata.AddCategory(GeometryModel3D.MaterialProperty, Category_Materials);
			Metadata.AddCategory(GlyphRunDrawing.ForegroundBrushProperty, Category_Appearance);
			Metadata.AddCategory(Glyphs.FillProperty, Category_Appearance);
			Metadata.AddCategory(Glyphs.FontRenderingEmSizeProperty, Category_Text);
			Metadata.AddCategory(Glyphs.FontUriProperty, Category_Text);
			Metadata.AddCategory(GradientStop.ColorProperty, Category_Appearance);
			Metadata.AddCategory(Grid.ColumnProperty, Category_Layout);
			Metadata.AddCategory(Grid.ColumnSpanProperty, Category_Layout);
			Metadata.AddCategory(Grid.IsSharedSizeScopeProperty, Category_Layout);
			Metadata.AddCategory(Grid.RowProperty, Category_Layout);
			Metadata.AddCategory(Grid.RowSpanProperty, Category_Layout);
			Metadata.AddCategory(Grid.ShowGridLinesProperty, Category_Layout);
			Metadata.AddCategory(GridSplitter.DragIncrementProperty, Category_Common_Properties);
			Metadata.AddCategory(GridSplitter.ResizeBehaviorProperty, Category_Common_Properties);
			Metadata.AddCategory(GridSplitter.ResizeDirectionProperty, Category_Common_Properties);
			Metadata.AddCategory(GridSplitter.ShowsPreviewProperty, Category_Common_Properties);
			Metadata.AddCategory(HeaderedContentControl.HeaderProperty, Category_Common_Properties);
			Metadata.AddCategory(HeaderedContentControl.HeaderTemplateProperty, Category_Misc);
			Metadata.AddCategory(HeaderedContentControl.HeaderTemplateSelectorProperty, Category_Misc);
			Metadata.AddCategory(Image.SourceProperty, Category_Common_Properties);
			Metadata.AddCategory(InkCanvas.EditingModeProperty, Category_Common_Properties);
			Metadata.AddCategory(Inline.TextDecorationsProperty, Category_Text);
			Metadata.AddCategory(ItemsControl.DisplayMemberPathProperty, Category_Common_Properties);
			Metadata.AddCategory(ItemsControl.IsTextSearchEnabledProperty, Category_Common_Properties);
			Metadata.AddCategory(ItemsControl.ItemContainerStyleProperty, Category_Misc);
			Metadata.AddCategory(ItemsControl.ItemContainerStyleSelectorProperty, Category_Misc);
			Metadata.AddCategory(ItemsControl.ItemsSourceProperty, Category_Common_Properties);
			Metadata.AddCategory(ItemsControl.ItemTemplateProperty, Category_Misc);
			Metadata.AddCategory(ItemsControl.ItemTemplateSelectorProperty, Category_Misc);
			Metadata.AddCategory(Light.ColorProperty, Category_Light);
			Metadata.AddCategory(Line.X1Property, Category_Appearance);
			Metadata.AddCategory(Line.X2Property, Category_Appearance);
			Metadata.AddCategory(Line.Y1Property, Category_Appearance);
			Metadata.AddCategory(Line.Y2Property, Category_Appearance);
			Metadata.AddCategory(LineGeometry.EndPointProperty, Category_Layout);
			Metadata.AddCategory(LineGeometry.StartPointProperty, Category_Layout);
			Metadata.AddCategory(MediaElement.BalanceProperty, Category_Media);
			Metadata.AddCategory(MediaElement.IsMutedProperty, Category_Media);
			Metadata.AddCategory(MediaElement.LoadedBehaviorProperty, Category_Media);
			Metadata.AddCategory(MediaElement.ScrubbingEnabledProperty, Category_Media);
			Metadata.AddCategory(MediaElement.SourceProperty, Category_Media);
			Metadata.AddCategory(MediaElement.UnloadedBehaviorProperty, Category_Media);
			Metadata.AddCategory(MediaElement.VolumeProperty, Category_Media);
			Metadata.AddCategory(MenuItem.IconProperty, Category_Common_Properties);
			Metadata.AddCategory(MenuItem.IsCheckableProperty, Category_Common_Properties);
			Metadata.AddCategory(MenuItem.IsHighlightedProperty, Category_Common_Properties);
			Metadata.AddCategory(MenuItem.IsPressedProperty, Category_Common_Properties);
			Metadata.AddCategory(MenuItem.IsSubmenuOpenProperty, Category_Common_Properties);
			Metadata.AddCategory(Model3D.TransformProperty, Category_Transform);
			Metadata.AddCategory(OrthographicCamera.WidthProperty, Category_Camera);
			Metadata.AddCategory(Page.TitleProperty, Category_Common_Properties);
			Metadata.AddCategory(Panel.BackgroundProperty, Category_Brushes);
			Metadata.AddCategory(Panel.IsItemsHostProperty, Category_Common_Properties);
			Metadata.AddCategory(Panel.ZIndexProperty, Category_Layout);
			Metadata.AddCategory(PasswordBox.PasswordCharProperty, Category_Text);
			Metadata.AddCategory(Path.DataProperty, Category_Appearance);
			Metadata.AddCategory(PathGeometry.FillRuleProperty, Category_Appearance);
			Metadata.AddCategory(PathSegment.IsStrokedProperty, Category_Appearance);
			Metadata.AddCategory(Pen.BrushProperty, Category_Appearance);
			Metadata.AddCategory(Pen.DashCapProperty, Category_Appearance);
			Metadata.AddCategory(Pen.DashStyleProperty, Category_Appearance);
			Metadata.AddCategory(PerspectiveCamera.FieldOfViewProperty, Category_Camera);
			Metadata.AddCategory(PointLightBase.ConstantAttenuationProperty, Category_Light);
			Metadata.AddCategory(PointLightBase.LinearAttenuationProperty, Category_Light);
			Metadata.AddCategory(PointLightBase.PositionProperty, Category_Light);
			Metadata.AddCategory(PointLightBase.QuadraticAttenuationProperty, Category_Light);
			Metadata.AddCategory(PointLightBase.RangeProperty, Category_Light);
			Metadata.AddCategory(Polygon.FillRuleProperty, Category_Appearance);
			Metadata.AddCategory(Polygon.PointsProperty, Category_Appearance);
			Metadata.AddCategory(Polyline.FillRuleProperty, Category_Appearance);
			Metadata.AddCategory(Polyline.PointsProperty, Category_Appearance);
			Metadata.AddCategory(Popup.CustomPopupPlacementCallbackProperty, Category_Misc);
			Metadata.AddCategory(Popup.HasDropShadowProperty, Category_Appearance);
			Metadata.AddCategory(Popup.HorizontalOffsetProperty, Category_Layout);
			Metadata.AddCategory(Popup.IsOpenProperty, Category_Common_Properties);
			Metadata.AddCategory(Popup.PlacementProperty, Category_Layout);
			Metadata.AddCategory(Popup.PlacementRectangleProperty, Category_Misc);
			Metadata.AddCategory(Popup.PlacementTargetProperty, Category_Misc);
			Metadata.AddCategory(Popup.StaysOpenProperty, Category_Common_Properties);
			Metadata.AddCategory(Popup.VerticalOffsetProperty, Category_Layout);
			Metadata.AddCategory(ProgressBar.IsIndeterminateProperty, Category_Common_Properties);
			Metadata.AddCategory(ProgressBar.OrientationProperty, Category_Common_Properties);
			Metadata.AddCategory(ProjectionCamera.FarPlaneDistanceProperty, Category_Camera);
			Metadata.AddCategory(ProjectionCamera.LookDirectionProperty, Category_Camera);
			Metadata.AddCategory(ProjectionCamera.NearPlaneDistanceProperty, Category_Camera);
			Metadata.AddCategory(ProjectionCamera.PositionProperty, Category_Camera);
			Metadata.AddCategory(ProjectionCamera.UpDirectionProperty, Category_Camera);
			Metadata.AddCategory(RadialGradientBrush.CenterProperty, Category_Layout);
			Metadata.AddCategory(RadioButton.GroupNameProperty, Category_Common_Properties);
			Metadata.AddCategory(RangeBase.LargeChangeProperty, Category_Common_Properties);
			Metadata.AddCategory(RangeBase.MaximumProperty, Category_Common_Properties);
			Metadata.AddCategory(RangeBase.MinimumProperty, Category_Common_Properties);
			Metadata.AddCategory(RangeBase.SmallChangeProperty, Category_Common_Properties);
			Metadata.AddCategory(RangeBase.ValueProperty, Category_Common_Properties);
			Metadata.AddCategory(Rectangle.RadiusXProperty, Category_Appearance);
			Metadata.AddCategory(Rectangle.RadiusYProperty, Category_Appearance);
			Metadata.AddCategory(RotateTransform.AngleProperty, Category_Transform);
			Metadata.AddCategory(RotateTransform.CenterXProperty, Category_Transform);
			Metadata.AddCategory(RotateTransform.CenterYProperty, Category_Transform);
			Metadata.AddCategory(RowDefinition.HeightProperty, Category_Layout);
			Metadata.AddCategory(RowDefinition.MaxHeightProperty, Category_Layout);
			Metadata.AddCategory(RowDefinition.MinHeightProperty, Category_Layout);
			Metadata.AddCategory(ScrollBar.OrientationProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.CanContentScrollProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.ComputedHorizontalScrollBarVisibilityProperty, Category_Appearance);
			Metadata.AddCategory(ScrollViewer.ComputedVerticalScrollBarVisibilityProperty, Category_Appearance);
			Metadata.AddCategory(ScrollViewer.ExtentHeightProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.ExtentWidthProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.HorizontalOffsetProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.HorizontalScrollBarVisibilityProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.ScrollableHeightProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.ScrollableWidthProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.VerticalOffsetProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.VerticalScrollBarVisibilityProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.ViewportHeightProperty, Category_Layout);
			Metadata.AddCategory(ScrollViewer.ViewportWidthProperty, Category_Layout);
			Metadata.AddCategory(Selector.IsSynchronizedWithCurrentItemProperty, Category_Common_Properties);
			Metadata.AddCategory(Selector.SelectedIndexProperty, Category_Common_Properties);
			Metadata.AddCategory(Selector.SelectedItemProperty, Category_Common_Properties);
			Metadata.AddCategory(Selector.SelectedValuePathProperty, Category_Common_Properties);
			Metadata.AddCategory(Selector.SelectedValueProperty, Category_Common_Properties);
			Metadata.AddCategory(Shape.FillProperty, Category_Brushes);
			Metadata.AddCategory(Shape.StretchProperty, Category_Appearance);
			Metadata.AddCategory(Shape.StrokeDashArrayProperty, Category_Appearance);
			Metadata.AddCategory(Shape.StrokeDashCapProperty, Category_Appearance);
			Metadata.AddCategory(Shape.StrokeDashOffsetProperty, Category_Appearance);
			Metadata.AddCategory(Shape.StrokeEndLineCapProperty, Category_Appearance);
			Metadata.AddCategory(Shape.StrokeLineJoinProperty, Category_Appearance);
			Metadata.AddCategory(Shape.StrokeMiterLimitProperty, Category_Appearance);
			Metadata.AddCategory(Shape.StrokeProperty, Category_Brushes);
			Metadata.AddCategory(Shape.StrokeStartLineCapProperty, Category_Appearance);
			Metadata.AddCategory(Shape.StrokeThicknessProperty, Category_Appearance);
			Metadata.AddCategory(SkewTransform.AngleXProperty, Category_Transform);
			Metadata.AddCategory(SkewTransform.AngleYProperty, Category_Transform);
			Metadata.AddCategory(SkewTransform.CenterXProperty, Category_Transform);
			Metadata.AddCategory(SkewTransform.CenterYProperty, Category_Transform);
			Metadata.AddCategory(Slider.AutoToolTipPlacementProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.AutoToolTipPrecisionProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.IsDirectionReversedProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.IsMoveToPointEnabledProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.IsSelectionRangeEnabledProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.IsSnapToTickEnabledProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.OrientationProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.SelectionEndProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.SelectionStartProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.TickFrequencyProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.TickPlacementProperty, Category_Common_Properties);
			Metadata.AddCategory(Slider.TicksProperty, Category_Common_Properties);
			Metadata.AddCategory(SolidColorBrush.ColorProperty, Category_Appearance);
			Metadata.AddCategory(SpecularMaterial.BrushProperty, Category_Appearance);
			Metadata.AddCategory(SpotLight.DirectionProperty, Category_Light);
			Metadata.AddCategory(SpotLight.InnerConeAngleProperty, Category_Light);
			Metadata.AddCategory(SpotLight.OuterConeAngleProperty, Category_Light);
			Metadata.AddCategory(StackPanel.OrientationProperty, Category_Layout);
			Metadata.AddCategory(StickyNoteControl.CaptionFontFamilyProperty, Category_Text);
			Metadata.AddCategory(StickyNoteControl.CaptionFontSizeProperty, Category_Text);
			Metadata.AddCategory(StickyNoteControl.CaptionFontStretchProperty, Category_Text);
			Metadata.AddCategory(StickyNoteControl.CaptionFontStyleProperty, Category_Text);
			Metadata.AddCategory(StickyNoteControl.CaptionFontWeightProperty, Category_Text);
			Metadata.AddCategory(TabControl.ContentTemplateProperty, Category_Misc);
			Metadata.AddCategory(TabControl.ContentTemplateSelectorProperty, Category_Misc);
			Metadata.AddCategory(TabControl.SelectedContentTemplateProperty, Category_Misc);
			Metadata.AddCategory(TabControl.SelectedContentTemplateSelectorProperty, Category_Misc);
			Metadata.AddCategory(TabControl.TabStripPlacementProperty, Category_Common_Properties);
			Metadata.AddCategory(Table.CellSpacingProperty, Category_Layout);
			Metadata.AddCategory(TableCell.ColumnSpanProperty, Category_Layout);
			Metadata.AddCategory(TableColumn.WidthProperty, Category_Layout);
			Metadata.AddCategory(TextBlock.TextProperty, Category_Common_Properties);
			Metadata.AddCategory(TextBlock.TextTrimmingProperty, Category_Text);
			Metadata.AddCategory(TextBlock.TextWrappingProperty, Category_Text);
			Metadata.AddCategory(TextBox.CharacterCasingProperty, Category_Text);
			Metadata.AddCategory(TextBox.MaxLengthProperty, Category_Text);
			Metadata.AddCategory(TextBox.MaxLinesProperty, Category_Text);
			Metadata.AddCategory(TextBox.MinLinesProperty, Category_Text);
			Metadata.AddCategory(TextBox.TextProperty, Category_Common_Properties);
			Metadata.AddCategory(TextBoxBase.AcceptsTabProperty, Category_Text);
			Metadata.AddCategory(TextBoxBase.AutoWordSelectionProperty, Category_Text);
			Metadata.AddCategory(TextBoxBase.IsUndoEnabledProperty, Category_Text);
			Metadata.AddCategory(TextEffect.ClipProperty, Category_Appearance);
			Metadata.AddCategory(TextEffect.ForegroundProperty, Category_Appearance);
			Metadata.AddCategory(TextElement.BackgroundProperty, Category_Brushes);
			Metadata.AddCategory(TextElement.FontFamilyProperty, Category_Text);
			Metadata.AddCategory(TextElement.FontSizeProperty, Category_Text);
			Metadata.AddCategory(TextElement.FontStretchProperty, Category_Text);
			Metadata.AddCategory(TextElement.FontStyleProperty, Category_Text);
			Metadata.AddCategory(TextElement.FontWeightProperty, Category_Text);
			Metadata.AddCategory(TextElement.ForegroundProperty, Category_Brushes);
			Metadata.AddCategory(TextElement.TextEffectsProperty, Category_Text);
			Metadata.AddCategory(TickBar.FillProperty, Category_Appearance);
			Metadata.AddCategory(TileBrush.AlignmentXProperty, Category_Layout);
			Metadata.AddCategory(TileBrush.AlignmentYProperty, Category_Layout);
			Metadata.AddCategory(ToggleButton.IsCheckedProperty, Category_Common_Properties);
			Metadata.AddCategory(ToggleButton.IsThreeStateProperty, Category_Common_Properties);
			Metadata.AddCategory(TransformGroup.ChildrenProperty, Category_Transform);
			Metadata.AddCategory(TranslateTransform.XProperty, Category_Layout);
			Metadata.AddCategory(TranslateTransform.YProperty, Category_Layout);
			Metadata.AddCategory(TreeViewItem.IsSelectedProperty, Category_Common_Properties);
			Metadata.AddCategory(UIElement.BitmapEffectInputProperty, Category_Appearance);
			Metadata.AddCategory(UIElement.BitmapEffectProperty, Category_Appearance);
			Metadata.AddCategory(UIElement.ClipToBoundsProperty, Category_Appearance);
			Metadata.AddCategory(UIElement.FocusableProperty, Category_Common_Properties);
			Metadata.AddCategory(UIElement.IsEnabledProperty, Category_Common_Properties);
			Metadata.AddCategory(UIElement.IsFocusedProperty, Category_Common_Properties);
			Metadata.AddCategory(UIElement.IsHitTestVisibleProperty, Category_Common_Properties);
			Metadata.AddCategory(UIElement.IsKeyboardFocusedProperty, Category_Common_Properties);
			Metadata.AddCategory(UIElement.IsMouseOverProperty, Category_Common_Properties);
			Metadata.AddCategory(UIElement.IsStylusDirectlyOverProperty, Category_Common_Properties);
			Metadata.AddCategory(UIElement.OpacityMaskProperty, Category_Brushes);
			Metadata.AddCategory(UIElement.OpacityProperty, Category_Appearance);
			Metadata.AddCategory(UIElement.RenderTransformProperty, Category_Transform);
			Metadata.AddCategory(UIElement.SnapsToDevicePixelsProperty, Category_Appearance);
			Metadata.AddCategory(UIElement.VisibilityProperty, Category_Appearance);
			Metadata.AddCategory(UniformGrid.ColumnsProperty, Category_Common_Properties);
			Metadata.AddCategory(UniformGrid.RowsProperty, Category_Common_Properties);
			Metadata.AddCategory(Viewbox.StretchDirectionProperty, Category_Appearance);
			Metadata.AddCategory(Viewbox.StretchProperty, Category_Appearance);
			Metadata.AddCategory(VirtualizingStackPanel.OrientationProperty, Category_Layout);
			Metadata.AddCategory(Window.AllowsTransparencyProperty, Category_Appearance);
			Metadata.AddCategory(Window.IconProperty, Category_Common_Properties);
			Metadata.AddCategory(Window.ResizeModeProperty, Category_Common_Properties);
			Metadata.AddCategory(Window.ShowInTaskbarProperty, Category_Common_Properties);
			Metadata.AddCategory(Window.SizeToContentProperty, Category_Common_Properties);
			Metadata.AddCategory(Window.TitleProperty, Category_Common_Properties);
			Metadata.AddCategory(Window.TopmostProperty, Category_Common_Properties);
			Metadata.AddCategory(Window.WindowStateProperty, Category_Common_Properties);
			Metadata.AddCategory(Window.WindowStyleProperty, Category_Appearance);
			Metadata.AddCategory(WrapPanel.ItemHeightProperty, Category_Layout);
			Metadata.AddCategory(WrapPanel.ItemWidthProperty, Category_Layout);

			Metadata.AddAdvancedProperty(Block.BreakColumnBeforeProperty);
			Metadata.AddAdvancedProperty(Block.BreakPageBeforeProperty);
			Metadata.AddAdvancedProperty(Block.PaddingProperty);
			Metadata.AddAdvancedProperty(ColumnDefinition.MaxWidthProperty);
			Metadata.AddAdvancedProperty(ColumnDefinition.MinWidthProperty);
			Metadata.AddAdvancedProperty(ComboBox.StaysOpenOnEditProperty);
			Metadata.AddAdvancedProperty(ComboBox.TextProperty);
			Metadata.AddAdvancedProperty(Control.HorizontalContentAlignmentProperty);
			Metadata.AddAdvancedProperty(Control.PaddingProperty);
			Metadata.AddAdvancedProperty(Control.VerticalContentAlignmentProperty);
			Metadata.AddAdvancedProperty(DashStyle.DashesProperty);
			Metadata.AddAdvancedProperty(DocumentViewer.ExtentHeightProperty);
			Metadata.AddAdvancedProperty(DocumentViewer.ExtentWidthProperty);
			Metadata.AddAdvancedProperty(DocumentViewer.HorizontalOffsetProperty);
			Metadata.AddAdvancedProperty(DocumentViewer.HorizontalPageSpacingProperty);
			Metadata.AddAdvancedProperty(DocumentViewer.ViewportHeightProperty);
			Metadata.AddAdvancedProperty(DocumentViewer.ViewportWidthProperty);
			Metadata.AddAdvancedProperty(DrawingGroup.ClipGeometryProperty);
			Metadata.AddAdvancedProperty(Figure.CanDelayPlacementProperty);
			Metadata.AddAdvancedProperty(Figure.HorizontalAnchorProperty);
			Metadata.AddAdvancedProperty(Figure.HorizontalOffsetProperty);
			Metadata.AddAdvancedProperty(Figure.VerticalAnchorProperty);
			Metadata.AddAdvancedProperty(Figure.VerticalOffsetProperty);
			Metadata.AddAdvancedProperty(FlowDocument.ColumnGapProperty);
			Metadata.AddAdvancedProperty(FlowDocument.ColumnRuleBrushProperty);
			Metadata.AddAdvancedProperty(FlowDocument.ColumnRuleWidthProperty);
			Metadata.AddAdvancedProperty(FlowDocument.ColumnWidthProperty);
			Metadata.AddAdvancedProperty(FlowDocument.IsColumnWidthFlexibleProperty);
			Metadata.AddAdvancedProperty(FormatConvertedBitmap.AlphaThresholdProperty);
			Metadata.AddAdvancedProperty(FrameworkElement.ActualHeightProperty);
			Metadata.AddAdvancedProperty(FrameworkElement.ActualWidthProperty);
			Metadata.AddAdvancedProperty(FrameworkElement.LayoutTransformProperty);
			Metadata.AddAdvancedProperty(FrameworkElement.MaxHeightProperty);
			Metadata.AddAdvancedProperty(FrameworkElement.MaxWidthProperty);
			Metadata.AddAdvancedProperty(FrameworkElement.MinHeightProperty);
			Metadata.AddAdvancedProperty(FrameworkElement.MinWidthProperty);
			Metadata.AddAdvancedProperty(FrameworkElement.TagProperty);
			Metadata.AddAdvancedProperty(GeometryGroup.FillRuleProperty);
			Metadata.AddAdvancedProperty(Glyphs.FontRenderingEmSizeProperty);
			Metadata.AddAdvancedProperty(Glyphs.FontUriProperty);
			Metadata.AddAdvancedProperty(Grid.IsSharedSizeScopeProperty);
			Metadata.AddAdvancedProperty(Grid.ShowGridLinesProperty);
			Metadata.AddAdvancedProperty(ItemsControl.DisplayMemberPathProperty);
			Metadata.AddAdvancedProperty(ItemsControl.IsTextSearchEnabledProperty);
			Metadata.AddAdvancedProperty(MediaElement.LoadedBehaviorProperty);
			Metadata.AddAdvancedProperty(MediaElement.ScrubbingEnabledProperty);
			Metadata.AddAdvancedProperty(MediaElement.UnloadedBehaviorProperty);
			Metadata.AddAdvancedProperty(PasswordBox.PasswordCharProperty);
			Metadata.AddAdvancedProperty(PathGeometry.FillRuleProperty);
			Metadata.AddAdvancedProperty(PathSegment.IsStrokedProperty);
			Metadata.AddAdvancedProperty(Pen.DashCapProperty);
			Metadata.AddAdvancedProperty(Pen.DashStyleProperty);
			Metadata.AddAdvancedProperty(RowDefinition.MaxHeightProperty);
			Metadata.AddAdvancedProperty(RowDefinition.MinHeightProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.CanContentScrollProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.CanContentScrollProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.ComputedHorizontalScrollBarVisibilityProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.ComputedVerticalScrollBarVisibilityProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.ExtentHeightProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.ExtentWidthProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.HorizontalOffsetProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.HorizontalScrollBarVisibilityProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.ScrollableHeightProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.ScrollableWidthProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.VerticalOffsetProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.VerticalScrollBarVisibilityProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.ViewportHeightProperty);
			Metadata.AddAdvancedProperty(ScrollViewer.ViewportWidthProperty);
			Metadata.AddAdvancedProperty(Selector.SelectedItemProperty);
			Metadata.AddAdvancedProperty(Selector.SelectedValuePathProperty);
			Metadata.AddAdvancedProperty(Selector.SelectedValueProperty);
			Metadata.AddAdvancedProperty(Shape.StretchProperty);
			Metadata.AddAdvancedProperty(Shape.StrokeDashArrayProperty);
			Metadata.AddAdvancedProperty(Shape.StrokeDashCapProperty);
			Metadata.AddAdvancedProperty(Shape.StrokeDashOffsetProperty);
			Metadata.AddAdvancedProperty(Shape.StrokeEndLineCapProperty);
			Metadata.AddAdvancedProperty(Shape.StrokeLineJoinProperty);
			Metadata.AddAdvancedProperty(Shape.StrokeMiterLimitProperty);
			Metadata.AddAdvancedProperty(Shape.StrokeStartLineCapProperty);
			Metadata.AddAdvancedProperty(SkewTransform.CenterXProperty);
			Metadata.AddAdvancedProperty(SkewTransform.CenterYProperty);
			Metadata.AddAdvancedProperty(Slider.AutoToolTipPrecisionProperty);
			Metadata.AddAdvancedProperty(Slider.IsMoveToPointEnabledProperty);
			Metadata.AddAdvancedProperty(Slider.IsSelectionRangeEnabledProperty);
			Metadata.AddAdvancedProperty(Slider.IsSnapToTickEnabledProperty);
			Metadata.AddAdvancedProperty(Slider.SelectionEndProperty);
			Metadata.AddAdvancedProperty(Slider.SelectionStartProperty);
			Metadata.AddAdvancedProperty(Slider.TicksProperty);
			Metadata.AddAdvancedProperty(TextBlock.TextTrimmingProperty);
			Metadata.AddAdvancedProperty(TextBlock.TextWrappingProperty);
			Metadata.AddAdvancedProperty(TextBox.CharacterCasingProperty);
			Metadata.AddAdvancedProperty(TextBox.MaxLengthProperty);
			Metadata.AddAdvancedProperty(TextBox.MaxLinesProperty);
			Metadata.AddAdvancedProperty(TextBox.MinLinesProperty);
			Metadata.AddAdvancedProperty(TextBoxBase.AcceptsTabProperty);
			Metadata.AddAdvancedProperty(TextBoxBase.AutoWordSelectionProperty);
			Metadata.AddAdvancedProperty(TextBoxBase.IsUndoEnabledProperty);
			Metadata.AddAdvancedProperty(TextEffect.ClipProperty);
			Metadata.AddAdvancedProperty(TextElement.FontStretchProperty);
			Metadata.AddAdvancedProperty(TextElement.FontStyleProperty);
			Metadata.AddAdvancedProperty(TextElement.FontWeightProperty);
			Metadata.AddAdvancedProperty(TextElement.TextEffectsProperty);
			Metadata.AddAdvancedProperty(UIElement.BitmapEffectInputProperty);
			Metadata.AddAdvancedProperty(UIElement.BitmapEffectProperty);
			Metadata.AddAdvancedProperty(UIElement.ClipToBoundsProperty);
			Metadata.AddAdvancedProperty(UIElement.FocusableProperty);
			Metadata.AddAdvancedProperty(UIElement.IsHitTestVisibleProperty);
			Metadata.AddAdvancedProperty(UIElement.SnapsToDevicePixelsProperty);

			Metadata.AddValueRange(Block.LineHeightProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(Canvas.BottomProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Canvas.LeftProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Canvas.TopProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Canvas.RightProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(ColumnDefinition.MaxWidthProperty, 0, double.PositiveInfinity);
			Metadata.AddValueRange(DocumentViewer.MaxPagesAcrossProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(Figure.HorizontalOffsetProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Figure.VerticalOffsetProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(FlowDocument.MaxPageWidthProperty, 0, double.PositiveInfinity);
			Metadata.AddValueRange(FlowDocument.MaxPageHeightProperty, 0, double.PositiveInfinity);
			Metadata.AddValueRange(FlowDocumentPageViewer.ZoomProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(FlowDocumentPageViewer.ZoomIncrementProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(FlowDocumentPageViewer.MinZoomProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(FlowDocumentPageViewer.MaxZoomProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(FrameworkElement.MaxHeightProperty, 0, double.PositiveInfinity);
			Metadata.AddValueRange(FrameworkElement.MaxWidthProperty, 0, double.PositiveInfinity);
			Metadata.AddValueRange(Grid.ColumnSpanProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(Grid.RowSpanProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(GridSplitter.KeyboardIncrementProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(GridSplitter.DragIncrementProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(InkCanvas.BottomProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(InkCanvas.TopProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(InkCanvas.RightProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(InkCanvas.LeftProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Line.Y2Property, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Line.X1Property, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Line.Y1Property, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Line.X2Property, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(List.MarkerOffsetProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(List.StartIndexProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(Paragraph.TextIndentProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(RangeBase.ValueProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(RangeBase.MaximumProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(RangeBase.MinimumProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(RepeatButton.IntervalProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(RowDefinition.MaxHeightProperty, 0, double.PositiveInfinity);
			Metadata.AddValueRange(Selector.SelectedIndexProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Slider.TickFrequencyProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Slider.SelectionStartProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(Slider.SelectionEndProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(TableCell.RowSpanProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(TableCell.ColumnSpanProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(TextBox.MinLinesProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(TextBox.MaxLinesProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(TextBoxBase.UndoLimitProperty, double.MinValue, double.MaxValue);
			Metadata.AddValueRange(TextElement.FontSizeProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(Timeline.SpeedRatioProperty, double.Epsilon, double.MaxValue);
			Metadata.AddValueRange(Timeline.DecelerationRatioProperty, 0, 1);
			Metadata.AddValueRange(Timeline.AccelerationRatioProperty, 0, 1);
			Metadata.AddValueRange(Track.ViewportSizeProperty, 0, double.PositiveInfinity);

			Metadata.AddValueRange(UIElement.OpacityProperty, 0, 1);

			Metadata.AddAdvancedProperty(typeof(Binding), "ValidationRules");
			Metadata.AddAdvancedProperty(typeof(Binding), "ValidatesOnExceptions");
			Metadata.AddAdvancedProperty(typeof(Binding), "ValidatesOnDataErrors");
			Metadata.AddAdvancedProperty(typeof(Binding), "NotifyOnSourceUpdated");
			Metadata.AddAdvancedProperty(typeof(Binding), "NotifyOnTargetUpdated");
			Metadata.AddAdvancedProperty(typeof(Binding), "NotifyOnValidationError");
			Metadata.AddAdvancedProperty(typeof(Binding), "ConverterParameter");
			Metadata.AddAdvancedProperty(typeof(Binding), "ConverterCulture");
			Metadata.AddAdvancedProperty(typeof(Binding), "Source");
			Metadata.AddAdvancedProperty(typeof(Binding), "RelativeSource");
			Metadata.AddAdvancedProperty(typeof(Binding), "IsAsync");
			Metadata.AddAdvancedProperty(typeof(Binding), "AsyncState");
			Metadata.AddAdvancedProperty(typeof(Binding), "BindsDirectlyToSource");
			Metadata.AddAdvancedProperty(typeof(Binding), "UpdateSourceExceptionFilter");
			Metadata.AddAdvancedProperty(typeof(BindingBase), "FallbackValue");
			Metadata.AddAdvancedProperty(typeof(BindingBase), "StringFormat");
			Metadata.AddAdvancedProperty(typeof(BindingBase), "TargetNullValue");
		}
	}
}
