//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------


using System;
using System.Drawing;
using SharpReportCore.Exporters;
/// <summary>
/// This Class handles Lines
/// </summary>
/// <remarks>
/// 	created by - Forstmeier Peter
/// 	created on - 28.09.2005 23:46:19
/// </remarks>
namespace SharpReportCore {
	
	public class BaseLineItem : SharpReportCore.BaseGraphicItem,IExportColumnBuilder {
		
		LineShape shape  = new LineShape();
		
		#region Constructor
		
		public BaseLineItem():base() {
		
		}
		
		#endregion
		
		#region IExportColumnBuilder  implementation
		
		public BaseExportColumn CreateExportColumn(Graphics graphics){	
			BaseStyleDecorator st = this.CreateItemStyle(graphics);
			ExportGraphic item = new ExportGraphic(st,false);
			return item;
		}
		
		private BaseStyleDecorator CreateItemStyle (Graphics g) {
			BaseStyleDecorator style = new BaseStyleDecorator();
			style.Shape = this.shape;
			style.Size = this.Size;
			style.Location = this.Location;
			style.BackColor = this.BackColor;
			style.ForeColor = this.ForeColor;
			style.Thickness = base.Thickness;
			style.DashStyle = base.DashStyle;
			return style;
		}
		
		#endregion
		public override void Render(ReportPageEventArgs rpea) {
			if (rpea == null) {
				throw new ArgumentNullException("rpea");
			}
			base.Render (rpea);
			RectangleF rect = base.DrawingRectangle (this.Size);
			shape.DrawShape (rpea.PrintPageEventArgs.Graphics,
			                 new BaseLine (this.ForeColor,base.DashStyle,base.Thickness),
			                 rect);
			
		}
		
		public override string ToString() {
			return "BaseLineItem";
		}
	}
}
