//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
//using System.Windows.Forms;
using System.Xml.Serialization;

/// <summary>
/// This Class is the BaseClass for <see cref="ReportSection"></see>
/// </summary>


namespace SharpReportCore {
	public class BaseSection : SharpReportCore.BaseReportObject {
		
		private int sectionMargin;
		
		private ReportItemCollection items;
		
		#region Constructors
		public BaseSection(): base() {
			this.Name = String.Empty;
		}
		
		public BaseSection (string sectionName) :base(){
			this.Name = sectionName;
		}
		
		#endregion
		
		
		
		#region properties
		

		public  int SectionMargin {
			get {
				return this.sectionMargin;
			}
			set {
				this.sectionMargin = value;
			}
		}
	
		
	
		[Browsable(false)]
		public ReportItemCollection Items{
			get {
				if (this.items == null) {
					items = new ReportItemCollection();
				}
				return items;
			}
		}
		#endregion
		
		#region System.IDisposable interface implementation
		public override void Dispose () {
			Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		~BaseSection(){
			Dispose(false);
		}
		
		protected override void Dispose(bool disposing) {
			try {
				if (disposing){
					if (this.items != null) {
						this.items.Clear();
						this.items = null;
					}
				}
			} finally {
				base.Dispose(disposing);
			}
		}
		
		#endregion
	}
}
